Feature/tidy ups
Electron-Labs/sha512 pull request #9
Opened 2022-03-24 08:56 UTC by noway

Removed unused files and added some documentation in README.md

2022-03-24 09:02 UTC, rahulghangas requested changes
LGTM, just one tiny nitpick

2022-03-24 09:02 UTC, rahulghangas commented on README.md
> +include "circomlib/binsum.circom"; // make sure to include binsum
Maybe change this to indicate that circomlib exists in node_modules

2022-03-24 09:03 UTC, rahulghangas commented
@noway and once again, thank you for your contribution!

2022-03-25 06:28 UTC, noway commented on README.md
> +include "circomlib/binsum.circom"; // make sure to include binsum
Changed the comment. I wanted to signify that you can use your own copy of binsum from your own local installation of circom. That's what I do for my project where I already have circom installed in a different path.

2022-03-25 07:17 UTC, merged